export const locales = ['en', 'es', 'fr', 'de', 'pt'] as const;
export type Locale = (typeof locales)[number];

type Translation = {
	meta_title: string; meta_description: string; hero_headline_1: string; hero_headline_2: string; hero_headline_3: string; hero_sub: string; cta_button: string; email_placeholder: string; reassurance: string; how_title: string; pricing_title: string; price_label: string; nav_how: string; nav_pricing: string; nav_signin: string; nav_start: string;
};

export const translations: Record<Locale, Translation> = {
	en: { meta_title: 'CancelKits — Cancel Subscriptions & Stop Recurring Charges Instantly', meta_description: 'CancelKits finds every subscription draining your money and cancels them in one click. Stop forgotten recurring charges. Free to start.', hero_headline_1: 'Cancel any subscription instantly —', hero_headline_2: "find what's draining you", hero_headline_3: '', hero_sub: 'The average American wastes $219/month on forgotten subscriptions. CancelKits finds them. CancelKits helps you cancel them.', cta_button: 'Find my subscriptions →', email_placeholder: 'you@example.com', reassurance: 'No credit card. Free subscription audit in 30 seconds.', how_title: 'How CancelKits finds and cancels your subscriptions', pricing_title: 'Simple, honest pricing.', price_label: 'per month', nav_how: 'How it works', nav_pricing: 'Pricing', nav_signin: 'Sign in', nav_start: 'Start free' },
	es: { meta_title: 'CancelKits — Cancela suscripciones y para cargos recurrentes', meta_description: 'CancelKits encuentra cada suscripción que te drena dinero y te ayuda a cancelarla. Empieza gratis, sin tarjeta.', hero_headline_1: 'Cancela cualquier suscripción —', hero_headline_2: 'descubre qué te está drenando', hero_headline_3: '', hero_sub: 'El estadounidense promedio desperdicia $219/mes en suscripciones olvidadas. CancelKits las encuentra y te ayuda a cancelarlas.', cta_button: 'Encontrar mis suscripciones →', email_placeholder: 'tu@correo.com', reassurance: 'Sin tarjeta. Auditoría gratis en 30 segundos.', how_title: 'Cómo CancelKits encuentra y cancela tus suscripciones', pricing_title: 'Precios simples y honestos.', price_label: 'al mes', nav_how: 'Cómo funciona', nav_pricing: 'Precios', nav_signin: 'Iniciar sesión', nav_start: 'Empezar gratis' },
	fr: { meta_title: 'CancelKits — Résiliez abonnements et arrêtez les prélèvements', meta_description: 'CancelKits trouve chaque abonnement qui vide votre compte et vous aide à le résilier. Gratuit pour commencer.', hero_headline_1: 'Résiliez tout abonnement —', hero_headline_2: 'voyez ce qui vous draine', hero_headline_3: '', hero_sub: 'L’Américain moyen gaspille 219 $/mois en abonnements oubliés. CancelKits les trouve et vous aide à les résilier.', cta_button: 'Trouver mes abonnements →', email_placeholder: 'vous@exemple.com', reassurance: 'Aucune carte. Audit gratuit en 30 secondes.', how_title: 'Comment CancelKits trouve et résilie vos abonnements', pricing_title: 'Des tarifs simples et honnêtes.', price_label: 'par mois', nav_how: 'Comment ça marche', nav_pricing: 'Tarifs', nav_signin: 'Se connecter', nav_start: 'Essayer gratuitement' },
	de: { meta_title: 'CancelKits — Abos kündigen & wiederkehrende Kosten stoppen', meta_description: 'CancelKits findet jedes Abo, das dich Geld kostet, und hilft beim Kündigen. Kostenlos starten — ohne Kreditkarte.', hero_headline_1: 'Jedes Abo sofort kündigen —', hero_headline_2: 'finde, was dich ausblutet', hero_headline_3: '', hero_sub: 'Der durchschnittliche Amerikaner verschwendet 219 $/Monat für vergessene Abos. CancelKits findet sie und hilft beim Kündigen.', cta_button: 'Meine Abos finden →', email_placeholder: 'du@beispiel.de', reassurance: 'Keine Kreditkarte. Kostenloser Check in 30 Sekunden.', how_title: 'So findet und kündigt CancelKits deine Abos', pricing_title: 'Einfach. Ehrlich. Transparent.', price_label: 'pro Monat', nav_how: 'So funktioniert’s', nav_pricing: 'Preise', nav_signin: 'Anmelden', nav_start: 'Kostenlos starten' },
	pt: { meta_title: 'CancelKits — Cancele assinaturas e pare cobranças recorrentes', meta_description: 'CancelKits encontra cada assinatura que drena seu dinheiro e ajuda a cancelar. Comece grátis, sem cartão.', hero_headline_1: 'Cancele qualquer assinatura —', hero_headline_2: 'veja o que está drenando você', hero_headline_3: '', hero_sub: 'O americano médio desperdiça US$219/mês em assinaturas esquecidas. CancelKits encontra e ajuda a cancelar.', cta_button: 'Encontrar minhas assinaturas →', email_placeholder: 'voce@exemplo.com', reassurance: 'Sem cartão. Auditoria grátis em 30 segundos.', how_title: 'Como o CancelKits encontra e cancela suas assinaturas', pricing_title: 'Preços simples e honestos.', price_label: 'por mês', nav_how: 'Como funciona', nav_pricing: 'Preços', nav_signin: 'Entrar', nav_start: 'Começar grátis' },
};
export type { Translation };
