export const locales = ['en', 'es', 'fr', 'de', 'pt'] as const;
export type Locale = (typeof locales)[number];

type Translation = {
	meta_title: string; meta_description: string; hero_headline_1: string; hero_headline_2: string; hero_headline_3: string; hero_sub: string; cta_button: string; email_placeholder: string; reassurance: string; how_title: string; pricing_title: string; price_label: string; nav_how: string; nav_pricing: string; nav_signin: string; nav_start: string;
};

export const translations: Record<Locale, Translation> = {
	en: { meta_title: 'CancelKit — Cancel subscriptions with confidence', meta_description: 'Find and cancel forgotten subscriptions in minutes.', hero_headline_1: "You're paying for", hero_headline_2: '8 subscriptions', hero_headline_3: 'you forgot about.', hero_sub: 'The average American wastes $219/month on forgotten subscriptions. CancelKit finds them. CancelKit kills them.', cta_button: 'Find my subscriptions →', email_placeholder: 'you@example.com', reassurance: 'No credit card. Scans in 30 seconds.', how_title: 'A clean exit, in three steps.', pricing_title: 'Simple, honest pricing.', price_label: 'per month', nav_how: 'How it works', nav_pricing: 'Pricing', nav_signin: 'Sign in', nav_start: 'Start free' },
	es: { meta_title: 'CancelKit — Cancela suscripciones fácilmente', meta_description: 'Encuentra y cancela suscripciones olvidadas en minutos.', hero_headline_1: 'Estás pagando por', hero_headline_2: '8 suscripciones', hero_headline_3: 'que olvidaste.', hero_sub: 'El estadounidense promedio desperdicia $219/mes en suscripciones olvidadas. CancelKit las encuentra. CancelKit las cancela.', cta_button: 'Encontrar mis suscripciones →', email_placeholder: 'tu@correo.com', reassurance: 'Sin tarjeta. Escaneo en 30 segundos.', how_title: 'Una salida limpia, en tres pasos.', pricing_title: 'Precios simples y honestos.', price_label: 'al mes', nav_how: 'Cómo funciona', nav_pricing: 'Precios', nav_signin: 'Iniciar sesión', nav_start: 'Empezar gratis' },
	fr: { meta_title: 'CancelKit — Résiliez vos abonnements facilement', meta_description: 'Trouvez et résiliez vos abonnements oubliés en quelques minutes.', hero_headline_1: 'Vous payez pour', hero_headline_2: '8 abonnements', hero_headline_3: 'que vous avez oubliés.', hero_sub: 'L’Américain moyen gaspille 219 $/mois en abonnements oubliés. CancelKit les trouve. CancelKit les résilie.', cta_button: 'Trouver mes abonnements →', email_placeholder: 'vous@exemple.com', reassurance: 'Aucune carte requise. Analyse en 30 secondes.', how_title: 'Une sortie nette, en trois étapes.', pricing_title: 'Des tarifs simples et honnêtes.', price_label: 'par mois', nav_how: 'Comment ça marche', nav_pricing: 'Tarifs', nav_signin: 'Se connecter', nav_start: 'Essayer gratuitement' },
	de: { meta_title: 'CancelKit — Abos einfach kündigen', meta_description: 'Finde und kündige vergessene Abonnements in wenigen Minuten.', hero_headline_1: 'Du zahlst für', hero_headline_2: '8 Abonnements', hero_headline_3: 'die du vergessen hast.', hero_sub: 'Der durchschnittliche Amerikaner verschwendet 219 $/Monat für vergessene Abos. CancelKit findet sie. CancelKit kündigt sie.', cta_button: 'Meine Abos finden →', email_placeholder: 'du@beispiel.de', reassurance: 'Keine Kreditkarte. Scan in 30 Sekunden.', how_title: 'Sauber raus, in drei Schritten.', pricing_title: 'Einfach. Ehrlich. Transparent.', price_label: 'pro Monat', nav_how: 'So funktioniert’s', nav_pricing: 'Preise', nav_signin: 'Anmelden', nav_start: 'Kostenlos starten' },
	pt: { meta_title: 'CancelKit — Cancele assinaturas facilmente', meta_description: 'Encontre e cancele assinaturas esquecidas em minutos.', hero_headline_1: 'Você está pagando por', hero_headline_2: '8 assinaturas', hero_headline_3: 'que esqueceu.', hero_sub: 'O americano médio desperdiça US$219/mês em assinaturas esquecidas. CancelKit encontra. CancelKit cancela.', cta_button: 'Encontrar minhas assinaturas →', email_placeholder: 'voce@exemplo.com', reassurance: 'Sem cartão. Análise em 30 segundos.', how_title: 'Uma saída simples, em três passos.', pricing_title: 'Preços simples e honestos.', price_label: 'por mês', nav_how: 'Como funciona', nav_pricing: 'Preços', nav_signin: 'Entrar', nav_start: 'Começar grátis' },
};

export type { Translation };
